const CHANGING_SEARCH_TEXT = "CHANGING_SEARCH_TEXT"
const VOTE_FOR_PAINTING = "VOTE_FOR_PAINTING"
const UPDATE_PAINTING = "UPDATE_PAINTING"

export {CHANGING_SEARCH_TEXT, VOTE_FOR_PAINTING, UPDATE_PAINTING}
